name: CICD
on:
  workflow_dispatch:
    inputs:
      environment: 
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging
jobs:
  code:
#    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "code clone from github"

  build: 
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: build docker container
        run: echo "docker container build"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: test the container
        run: echo "testing the container"
  deploy:
    if: inputs.environment == 'dev'
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: deploying the app
        run: echo "docker compose deployed the app"
      
