name: Hello workflow
on:
  push:
    branches: [main]
    paths: 
      - '**.html'
jobs:
  greet:
#    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "Hello Dosto"
