name: portfolio
on:
  push: 
    branches: [main]

permissions: 
  pages: write
  id-token: write
  contents: read
jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: actions/checkout@v4

      - name: Setup github pages
        run: actions/configure-pages@v4

      - name: upload static files
        run: actions/upload-static@v4

      - name: deploy to github pages
        run: actions/deploy-pages@v4
